# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7063706708097ab6fd3a5956890a2f5170ad29e2881bef567f16449aa3a7d26f42cc005fe3d35fa4ea6ae3498e3ea7cc9a935d5342d16dd9e75816afe9bc4462

test:
  secret_key_base: 4e252bd4e1c24f742150504f842bccdee28667ad2e8a82d88a47118ac2eff22bf283e5a08792a533e2618c86d12fc4f97a5c084d2ee10ad83d43838b28c83fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
